### ISSUE TITLE
Problem with german characters ß, ä, ö, ü, ... in addresses

### ISSUE THREAD

**Issue by johannstieger** [dailypenn/csv-geocoder#1]
Hi, when I wanna use adresses like "4720 Kallham, Geßwagen 1" then I get errors like this:
python3 geocoder.py Adressen.csv
Traceback (most recent call last):
  File "geocoder.py", line 41, in <module>
    response = urlopen(api_url)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1250, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.6/http/client.py", line 1117, in putrequest
    self._output(request.encode('ascii'))
UnicodeEncodeError: 'ascii' codec can't encode character '\xdf' in position 38: ordinal not in range(128)

Is there a way to solve this? Best regards, Johann

**Comment by alexwgraves** [comment]
Should be working now! The latest changes will URL-encode the address before passing it to Google's API, so that should fix the errors with any special characters. Let me know if there are any other issues!
